export const FLOATING_TAB_BAR_HEIGHT = 72;
export const FLOATING_TAB_MARGIN = 20;
export const CONTENT_BOTTOM_PADDING = FLOATING_TAB_BAR_HEIGHT + FLOATING_TAB_MARGIN + 12;
export const SIDEBAR_WIDTH = 96;
export const WIDE_LAYOUT_BREAKPOINT = 768;
